wip: bucket exercise event
valorem-labs-inc/clear-subgraph pull request #55
Opened 2023-09-04 19:54 UTC by nickadamson

2023-09-26 18:32 UTC, h0tw4t3r approved these changes
lgtm

2023-09-26 21:30 UTC, 0xAlcibiades approved these changes

2023-09-29 18:35 UTC, nickadamson commented on schema.graphql
> +  # The optionTypeId + index of bucket
```suggestion
  # The optionTypeId + index of bucket
  # `${optionId}-{bucketIndex}`
```

2023-10-09 03:06 UTC, 0xAlcibiades requested changes
This is not complete yet as per the discussion last week.

2023-10-09 04:35 UTC, merged